version: 0.1

volumes:
  wordpress_webfiles

networks:

services:
  nginx:
    container-name: nginx
    build: ./requirements/nginx/.
    image: greus-ro_nginx:1.0    
    volumes:
      -wordpress_webfiles:/var/www/:ro
    ports:
      -"9999:80"
    env-file: .env
    restart: always