#version: "3"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/gabriel/Dev/42/43_Inception/project/wordpress/
#    device: /mnt/inception/project/wordpress
      o:  bind
      type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/gabriel/Dev/42/43_Inception/project/mariadb/
#     device: /mnt/inception/project/mariadb
      #o : mount options
      o: bind
      #type of filesystem like nfs
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: greus-ro_nginx:1.0
    volumes:
      - wordpress:/var/www/html/:ro
    networks:
      - inception
    ports:
      - "443:443"
    hostname: "greus-ro.42.fr"
    env_file: ".env"
    restart: always
    
  mariadb:
    container_name: mariadb
    build:  ./requirements/mariadb/.
    image: greus-ro_mariadb:1.0
    volumes:
      - mariadb:/var/lib/mysql:rw
    networks:
      - inception
    env_file: ".env"
    restart: "always"
