#version: "3.5"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home/gabriel/Dev/42/43_Inception/wordpress/
      o:  bind
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: greus-ro_nginx:1.0
    volumes:
      - wordpress:/var/www/html/:ro
    networks:
     - inception
    ports:
      - "80:80"
    env_file: .env
    restart: always