#version: "3"

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
#      device: /home/gabriel/Dev/42/43_Inception/project/wordpress/
      device: /mnt/inception/project/wordpress
      o:  bind
      type: none

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: greus-ro_nginx:1.0
    volumes:
      - wordpress:/var/www/html/:ro
    networks:
      - inception
    ports:
      - "443:443"
    hostname: "greus-ro.42.fr"
    env_file: ".env"
    restart: always